### ISSUE TITLE
Grænsefladeønsker fra Metadata

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#109]
1) Teksten ”Find flere ord for …” kunne måske rettes til ”Søg flere ord for …”
2) Når man afslutter en hovedkategori og skal klikke videre til en ny, nævnes den næste hovedkategori ikke. F.eks. når man skal videre fra Fortælleteknik (Tempo) til Stemning står der ”Videre til positiv” nederst. 
3) Under Miljø i menuen til venstre er alle ord skrevet med stort. Det skal vel kun være det første ord der er skrevet med stort? 
4) Verbaliseret tid: tid er skrevet med stort.
5) Når man klikker på Handling er om i Handling om skrevet med stort.
6) Om i Skrivestil og struktur er skrevet med stort
7) Der står at man maksimalt skal vælge tre ord pr. kategori. Det er ikke muligt at fravælge kun tilvælge.

**Comment by KiraH** [comment]
testet OK
