### ISSUE TITLE
Kommentarer skal kunne trækkes ud af læsekompasset

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#121]
Der skal tilføjes dato til kommentarer i Metakompasset, som skal med i det listeudtræk, som Metadata får. 

Listen skal desuden sortes efter dato (nyeste først) og dato skal vises i udtrækket.  (Mindre rettelse til CBO)

**Comment by BettinaAndersen** [comment]
Tids-stempel kommer med ud nu. CBO skal i gang

**Comment by cboesgaard** [comment]
First shot er checket ind, så nu burde alle dataelementer være med:
https://metakompas.demo.dbc.dk/reports/comments.html

Mit gæt er at alle kommentarer til ordnes efter dato, men lad mig lige få det beskrevet.

**Comment by BettinaAndersen** [comment]
Ikke hørt noget fra Metadata. Lukkes for nu.
