### ISSUE TITLE
Rensning af metadata, så vi kun eksporterer tags, der findes i taxonomien

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/metakompasset#135]
Som eksempel skal "nutid" fjernes fra taxonomien, men tagget ligger på ca. 40 poster i metakompasset. Data skal ikke fjernes, men vi skal på eksporttidspunktet sikre, at alle tags, der eksporteres, findes i taxonomien.

**Comment by BettinaAndersen** [comment]
Hvorfor ikke fjerne data?

**Comment by AndersFriisBrodsgaard** [comment]
Kasper har tester og siger selv at det er heeeelt OK
