### ISSUE TITLE
Valg af beskrivende tekster

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#136]
På godkendelses-siden skal der vises forslag til nogle beskrivende tekster, hvoraf brugeren skal kunne vælge den bedste. 
Den beskrivende tekst skal gemmes i databasen (og senere også eksporteres til update).
Hvis brugeren "glemmer" at vælge en, skal en tekst vælges alligevel.

Det skal håndteres hvis der ikke er valgt nogle stemningsord

**Comment by AndersFriisBrodsgaard** [comment]
Portering af algoritme fra PY til Node
Se "dump_descriptions3" i https://github.com/DBCDK/metakompasset/blob/master/analysis/analyze.py
De prioriterede tags skal så vidt muligt bruges i sætningerne
Algoritmen arbejder med en række sætninger, navngivet fra "A" til "P", dvs. 16 sætningslogikker. 


Grænseflade: 
Vis beskrivende tekster til brugeren baseret på alle sætningslogikker (A-P), baseret på ovennævnte algoritme
Der skal evt. være mulighed for at reloade forslagene. Ved tryk på reload, reloades der ikke sætninger for det sætningslogikker, brugeren allerede har valgt. 
Brugeren skal vælge 2 sætninger (så længe der er tags til at danne sætningerne) vis fx checkboxes, hvor der kan vælges max 2 ad gangen.
Brugerens valg skal gemmes i DB i form af valgt sætningslogik (A-P) + ID'er for de tags, der er brugt i sætningen.
Hvis brugeren kommer tilbage for at redigere en post, vises de tidligere valgte sætninger og de er valgte som default.


Export
Ved eksport af værker fra Metakompasset, skal der genereres én tekststreng med de to udvalgte sætninger kombineret med et linebreak imellem. Property'en skal hedde "taxonomy_description".
Hvis der er mere end en inddatering på værket, skal sætningerne fra den seneste inddatering benyttes. 
De eksisterende poster har pt. ikke nogle sætninger, der er valgt af brugere. I de tilfælde skal der automatisk vælges to sætninger ved eksport.

**Comment by BettinaAndersen** [comment]
Lukkes da opdelt i stories #143, #144 og #145
