### ISSUE TITLE
Portering af sætningsalgoritme fra PY til Node

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/metakompasset#143]
Algoritmerne, som pt er skrevet i Python, skal overføres til Node. 
Se "dump_descriptions3" i https://github.com/DBCDK/metakompasset/blob/master/analysis/analyze.py
Algoritmerne arbejder med en række sætninger, navngivet fra "A" til "P", dvs. 16 sætningslogikker. 

Herudover skal de prioriterede tags så vidt muligt bruges i sætningskonstruktionerne, således at de vigtigste aspekter af værkerne afspejles i de beskrivende sætninger.

**Comment by KiraH** [comment]
ikke testbar i grænsefladen. Lukker den.
