### ISSUE TITLE
Grænseflade til valg af beskrivende sætninger

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/metakompasset#144]
- [x] Vis beskrivende tekster til brugeren baseret på alle sætningslogikker (A-P), baseret på algoritmerne i #143 Ud for hver sætning vises bogstav og en checkbox.
- [x] Der skal (evt.) være mulighed for at reloade forslagene og få nye variationer af sætningerne. Ved tryk på reload, reloades der ikke sætninger for det sætningslogikker, brugeren allerede har valgt.
- [x] Brugeren skal vælge 2 sætninger (så længe der er tags til at danne mindst 2 sætninger). Vis checkboxes, hvor der kan vælges max 2 ad gangen.
- [x] Brugerens valg skal gemmes i DB i form af valgt sætningslogikker (A-P) + ID'er for de tags, der er brugt i sætningerne. Således kan sætningerne senere bruges til at lave søgninger på de valgte tags.
- [x] Hvis brugeren vender tilbage for at redigere en post, vises de tidligere valgte sætninger og en række nye for de andre logikker. De tidligere valgte sætninger er selected som default.
- [x] *NY - Der skal ikke vises Bogstaver og linjer med manglende indhold. Brugeren skal kun præsenteres for de sætninger, som han kan vælge imellem.

**Comment by BettinaAndersen** [comment]
Efter demo i dag: Der skal ikke vises Bogstaver og linjer med manglende indhold. Brugeren skal kun præsenteres for de sætninger, som han kan vælge imellem.

**Comment by KiraH** [comment]
testet OK
