### ISSUE TITLE
Export af sætninger

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/metakompasset#145]
- [x] Ved eksport af værker fra Metakompasset skal der genereres én tekststreng, hvor de to brugervalgte sætninger kombineres med et linebreak imellem. Property'en skal hedde "taxonomy_description".
- [x] Hvis der er mere end en inddatering på et værk, skal sætningerne fra den seneste inddatering benyttes.
- [x] De eksisterende poster har pt. ikke nogen sætninger, der er brugervalgt. I de tilfælde skal der automatisk vælges/genereres to sætninger ved eksport, som derefter kombineres som beskrevet ovenfor.

Accept:
- taxonomy_description property er tilføjet til værker, når man går ind på exportWorks endpoint
- I content first matcher sætningerne med dem fra exportWorks (kan først testes når metakompas er rullet helt ud til prod)

**Comment by KiraH** [comment]
testes når #144 er færdig. Lukker denne.
