### ISSUE TITLE
'forladte steder' spøger under de andre "inddateringsfaner"

### ISSUE THREAD

**Issue by mtni** [DBCDK/metakompasset#157]
Når man er ved at inddatere metadata på et værk, og man under fanen `handing` -> `handler om` søger efter `for` og navigere videre ved eksempelvis at klikke på `fortællerteknik: Skrivestil og struktur >` i topppen til højre, vil `forladte steder` blive overført til toppen af de efterfølgende faners lister. 

Original beskrivelse (fra mail):
"I Metakompasset har jeg nu flere gange oplevet at "forladte steder" går igen på mange lister med termer. Det står to tre gange i toppen af listerne med valgmuligheder. Jeg tror det skyldes at jeg under "handler om" har søgt på "for". Men det bør jo ikke gå med videre."

![skaermbillede 2018-08-02 kl 16 32 33 2](https://user-images.githubusercontent.com/36037828/43765436-3972338a-9a30-11e8-886b-6aca4f0e9f80.png)

**Comment by kfudbc** [comment]
Der var to tags der havde id 6064. Højst sandsynligt har det været problemet.
Det ene har nu fået nyt id (ingen af dem har været brugt, så ingen problemer med det)
