### ISSUE TITLE
Metadata i brønden: understøttelse af promat-link

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/metakompasset#162]
Ved brug af promat-link skal man komme direkte til inddaterings-siden.
Linket må skulle indeholde en pid som vi kan bruge, og id på lektøren (medmindre alle lektører får et fælles id).

Derudover skal der i storeMaterial.api.js foretages et request til update, hvis brugeren er en lektør

**Comment by BettinaAndersen** [comment]
Det skal afklares hvad der leveres fra Promat/linket. Er det en PID eller FAUST? Og hvilken brønd skal der søges i for at få data.

**Comment by kfudbc** [comment]
Vi skal have afklaret, hvilket niveau af sikkerhed vi ønsker. Er det nok med et promat-link, hvor vi bare har et lektør-id og id på værket? Eller skal vi lave noget ticket-funktionalitet?

**Comment by BettinaAndersen** [comment]
Dette issue udgår, da ny beslutning er at lektører også skal logges ind. Der oprettes ny story til at håndtere Login for lektører.
