### ISSUE TITLE
Introsiden skal have en hjælpknap med adgang til vejledningsdokument

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#179]
Vejledningsdokumentet behøver blot åbnes som pdf i ny fane.

Vejledningsdokumentet er her vedhæftet som Word og pdf.:
[Vejledning til inddatering i metakompasset.docx](https://github.com/DBCDK/metakompasset/files/2405501/Vejledning.til.inddatering.i.metakompasset.docx)
[Vejledning til inddatering i metakompasset.pdf](https://github.com/DBCDK/metakompasset/files/2405502/Vejledning.til.inddatering.i.metakompasset.pdf)

**Comment by KiraH** [comment]
testet OK
