### ISSUE TITLE
Valg af titel-side: Søgeboks skal give fejlbesked, hvis der ikke kan hentes et resultat

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#180]
Lige nu gøre en spinner bare uendeligt. Der skal i stedet gives besked om at intet resultat er fundet.

**Comment by KiraH** [comment]
Der gives stadig ingen fejlbesked, hvis jeg søger på noget der ikke er der.

**Comment by KiraH** [comment]
Hov, der skulle lige rulles ud.
Testet OK.
