### ISSUE TITLE
Ændring af kategori-overskrifter

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#184]
"Handlingens tid" skal hedde "Handlingens tid i ord" og "Tid" skal navngives "Handlingens tid i tal", "Sted" skal hedde "Geografisk sted", "Hovedpersoner" skal hedde "Hovedperson(er), Karaktertræk skal hedde "Hovedpersonens karaktertræk", "Konflikt" skal hedde "Hovedpersonens konflikt"

**Comment by stanvins** [comment]
This was a pure dropbox, json file update. Ie. the taxonomy-v3.json file on dropbox is updated now with the changes and those changes are thus automatically implemented across  staging, production and live versions.

Closing issue.
