### ISSUE TITLE
Skift af tekst på introside

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#195]
På Login-siden https://metakompas.demo.dbc.dk/login skal teksten udskiftes med:

”Velkommen til Metakompasset. 
Metakompasset indeholder et vokabular til emne- og stemningsbeskrivelse af skønlitterære værker til brug i Læsekompasset. 
Ingen af kategorierne er obligatoriske – dvs. at der kan være kategorier, hvor det ikke er relevant at tildele emneord. I de tilfælde skal kategorien blot springes over. 
Du kan tildele det antal ord, du mener er relevant for beskrivelse af læseoplevelsen. Du skal vælge de ord, der er relevante i forhold til den læseoplevelse, du har haft og mener andre kan få.”

**Comment by KiraH** [comment]
testet OK
