### ISSUE TITLE
Hentning af metadata til given pid, faust eller isbn

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/metakompasset#4]
Når en pid er indtastet bør der hentes basale metadata via OpenPlatform og vises til brugeren sådan at vedkommende kan verificere at den givne `pid`, `faust` eller `isbn` er korrekt.

**Comment by kkdbc** [comment]
skal muligvis udvides til faust og isbn

**Comment by hrmoller** [comment]
@kkdbc klart. Har opdateret beskrivelse/overskrift
