### ISSUE TITLE
Ændringer i taxonomi skal fremhæves på siderne

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/metakompasset#53]
Hvis der sker ændringer i taxonomien, skal disse markeres med gult, så brugeren ved, hvor der er sket ændringer. Ændringerne skal vises i forhold til den version af taxonomien, som blev anvendt ved inddatering af værket.

**Comment by kfudbc** [comment]
Vi tilføjer ekstra information til taxonomi, fx:
"børn" bliver til
{title: "børn", status: "renamed", prevTitle: "kiddies"}

Muligheder for status: added, deleted, unchanged, renamed.
status skal også tilføjes til "sider/undersider"

**Comment by BettinaAndersen** [comment]
Bør testes med ny taxonomi-version.

**Comment by KiraH** [comment]
Både tilføjet taxonomi og ændret taxonomi får label renamed. 

Det bliver ikke markeret med gult, men med et (-) bagefter. 

Slettede får en streg over. Her er meningen helt klar.

**Comment by KiraH** [comment]
Lukker denne. Bugs oprettet i nyt issue, da det ikke prioriteres at få det rettet lige nu.
