### ISSUE TITLE
Kommentarer bliver overskrevet med INGENTING!

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/metakompasset#72]
Hvis man indlæser et værk man allerede har inddateret, bliver kommentar-felterne ikke indlæst korrekt. Dette medfører at kommentarerne ikke kommer med når man gemmer igen.

Kommentarerne findes dog stadig i databasen, da entries ikke bliver overskrevet.

Så buggen skal fixes, og så skal de gamle kommentarer overføres til seneste inddateringer......

**Comment by KiraH** [comment]
testet OK
