### ISSUE TITLE
Datapipeline

### ISSUE THREAD

**Issue by KiraH** [DBCDK/metakompasset#78]
Datapipeline skal tilpasses.
Ved indtastning af nye værker i Metakompas v.2 skal værkerne optræde i Content First grænsefladen og indeholde de nye metadata + data fra brønden.

**Comment by cboesgaard** [comment]
Jeg kapre denne her.

* jeg afhænger af at data er konverteret
* metadata antager jeg bliver lagt som før

Opgaven er at sørge for at der produceres samme artifakter som før (men med ny taxonomi), som kan bruges til ny content-first.

**Comment by kfudbc** [comment]
Der kommer en lille ændring til exportTags. I stedet for at have:
 selected: ["1", "2"]
vil den returnere:
selected: [{id: 1, score: 0}, {id: 2, score: 0}]

id'et er en integer. score er et udtryk for hvor vigtigt brugeren synes et tag er for bogen. Til at starte med vil den være 0 eller 1.

**Comment by KiraH** [comment]
Lukker denne.
