### ISSUE TITLE
Side til Miljø

### ISSUE THREAD

**Issue by KiraH** [DBCDK/metakompasset#80]
Der skal oprettet en "harmonikaside" til miljø, hvor man kan se de 2 øverste ord i hver kategori og folde resten ud og ind.

Her findes en liste med nogle eksempler på, som der kan tages udgangspunkt i.

**Comment by BettinaAndersen** [comment]
For at reducere yderligere kan punkterne under Miljø implementeres som "undersider" med samme struktur som de øvrige. Se forslag på design-light her: https://www.dropbox.com/sh/j0t1z5pfe0b0ylb/AAAxBdSSShyyzVVZvceYeec6a?dl=0
MetakompasV2Light.pdf

**Comment by KiraH** [comment]
OK
