### ISSUE TITLE
Stemninger

### ISSUE THREAD

**Issue by KiraH** [DBCDK/metakompasset#88]
Skal hver stemning have sin side?

Så skal denne måske splittes op.

**Comment by BettinaAndersen** [comment]
For at reducere yderligere kan punkterne under Stemning implementeres som "undersider" med samme struktur som de øvrige. Se forslag på design-light her: https://www.dropbox.com/sh/j0t1z5pfe0b0ylb/AAAxBdSSShyyzVVZvceYeec6a?dl=0
MetakompasV2Light.pdf
