### ISSUE TITLE
opsumering i højre side

### ISSUE THREAD

**Issue by KiraH** [DBCDK/metakompasset#89]
Der skal i højre side være en opsumering af hvilke kategorier der er udfyldt.

**Comment by BettinaAndersen** [comment]
Se forslag på design-light her: https://www.dropbox.com/sh/j0t1z5pfe0b0ylb/AAAxBdSSShyyzVVZvceYeec6a?dl=0
MetakompasV2Light.pdf

**Comment by BettinaAndersen** [comment]
Done
