### ISSUE TITLE
Afslutningsside

### ISSUE THREAD

**Issue by KiraH** [DBCDK/metakompasset#90]
Der skal være en afslutningsside, hvor man samlet kan se alle de ord der er valgt at knytte på værket.

Ud for hvert ord skal det være muligt at afmærke om det valgte ord er særligt vigtigt for værket.

**Comment by BettinaAndersen** [comment]
Se forslag på design-light her: https://www.dropbox.com/sh/j0t1z5pfe0b0ylb/AAAxBdSSShyyzVVZvceYeec6a?dl=0
MetakompasV2Light.pdf

**Comment by KiraH** [comment]
testet OK
