### ISSUE TITLE
Eksport af id'er og tilknyttede emneord  til Content First (og recommender)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#94]

**Comment by vibjerg** [comment]
Der er tilføjet et api endpoint /api/getTaxonomyMap som henter taxonomien ud med id som index. Kan evt. testes op http://metakompas-s01.dbc.dk:8000/api/getTaxonomyMap

**Comment by KiraH** [comment]
Testet at der ligger et dokument med id'er og emneord.
