### ISSUE TITLE
Filterside Metakompasset V.2

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/metakompasset#95]
Som aftalt oprettes dette issue i forhold til generel udvikling af den nye filter-side. 
Filtersiden skal bestå af sidemenu i venstreside, opsumering i højre side #89 , udvalgte emneord med check-bokse (hvis mere end 20 eksisterer kan disse søges frem) samt et notefelt, hvor brugeren kan indtaste forslag.

Se design her: https://www.dropbox.com/sh/j0t1z5pfe0b0ylb/AAAxBdSSShyyzVVZvceYeec6a?dl=0
MetakompasV2Light.pdf

Indholdsmæssigt skal der oprettes sider beskrevet i følgende issues.
#93 #92 #91 #88 #87 #83 #82 #81 #80  

- [x] inputfelt til filtrering hvis der er mere en 20 elementer
- [x] Vis de første 10 elementer på listen.
- [x] Vis valgte elementer som udgangspunkt (Skal de altid vises?)
- [x] Mulighed for at rydde filter.
- [x] Vis hvordan man hitter ved filtrering
- [x] Mulighed for at tilføje nye forslag til ord
   - [x] Sikre at forslag bliver gemt i db
- [ ] Skal der være mulighed for at vise flere ord på listen
- [x] Vis hvor mange ord der er i alt på listen.

**Comment by KiraH** [comment]
Når man søger en ny bog frem og klikker "OK" kommer metadata aldrig frem, der bliver ved at stå henter metadata.

Klikker man på en af de eksisterende bøger kan man godt komme videre.

Vælger man først en af de eksisterende bøger og søger derefter en ny bog frem, får man vist metadata fra den eksisterende bog, når man klikker "OK".

**Comment by KiraH** [comment]
testet OK
